### ISSUE TITLE
404 not-found error for the services

### ISSUE THREAD

**Issue by mertingen** [Kong/docker-kong-js-pdk#4]
In this config.yml file, services conf is like the following.

```
services:
  - name: example-service
    url: https://mockbin.org
    plugins:
      - name: clacks
 ```

I was getting 404 not found and I changed it like the following and it worked well. I think "paths" would be handled properly.

```
services:
  - url: https://mockbin.org
    routes:
      - paths:
          - "/"
    plugins:
      - name: clacks
```
